# Generated by Django 3.2.8 on 2023-01-07 22:15

from django.db import migrations, models
import django.db.models.deletion

def insert_init_data(apps, schema_editor):
    Canton = apps.get_model('app', 'Canton')
    Canton.objects.create(nombre='CELICA',latitud='-4.10266',longitud='-79.95665')
    Canton.objects.create(nombre='PINDAL',latitud='--4.1143',longitud='-80.10679')
    Canton.objects.create(nombre='ZAPOTILLO',latitud='-4.38636',longitud='-4.38636')

    TipoProductor = apps.get_model('app', 'Tipo_Productor')
    TipoProductor.objects.create(nombre='PEQUEÑO')
    TipoProductor.objects.create(nombre='MEDIANDO')
    TipoProductor.objects.create(nombre='GRANDE')

def update_init_data(apps, schema_editor):
    Canton = apps.get_model('app', 'Canton')
    Canton.objects.all().delete()

    TipoProductor = apps.get_model('app', 'Tipo_Productor')
    TipoProductor.objects.all().delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('latitud', models.CharField(max_length=250)),
                ('longitud', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costo_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(max_length=4, unique=True)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('activo', models.BooleanField(default=True)),
                ('recolectado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amontonado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desgranado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('alquiler_desgranadora', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ensacado_almacenamiento', models.DecimalField(decimal_places=2, max_digits=19)),
                ('control_tratamiento_maiz', models.DecimalField(decimal_places=2, max_digits=19)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=19)),
                ('cosecha_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primera_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primer_control_plagas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primer_control_enfermedades', models.DecimalField(decimal_places=2, max_digits=19)),
                ('aplicacion_hebricida', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segunda_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segundo_control_plagas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segundo_control_enfermedades', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tercera_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tiempo_espera', models.DecimalField(decimal_places=2, max_digits=19)),
                ('labores_culturales_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desbroce_monte', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quema_maleza', models.DecimalField(decimal_places=2, max_digits=19)),
                ('seleccion_semilla', models.DecimalField(decimal_places=2, max_digits=19)),
                ('aplicacion_herbicida', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desinfeccion_semilla', models.DecimalField(decimal_places=2, max_digits=19)),
                ('siembra', models.DecimalField(decimal_places=2, max_digits=19)),
                ('siembra_total', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fk_canton', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parroquiaslist', to='app.canton')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
    
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=11, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fk_canton', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cantonlist', to='app.canton')),
                ('fk_parroquia', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parroquialist', to='app.parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('hectareas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=19)),
                ('toneladas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quintales', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField()),
                ('fk_productor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='listarproductoresproduccion', to='app.productor')),
                ('fk_tipo_productor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tipoproductorlist', to='app.tipo_productor')),
            ],
        ),
        migrations.CreateModel(
            name='Intermediario_Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_compra', models.PositiveIntegerField(max_length=4)),
                ('cantidad_comprada', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('fk_intermediario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.intermediario')),
                ('fk_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.produccion')),
            ],
        ),
        migrations.RunPython(insert_init_data,update_init_data),
    ]
