# Generated by Django 3.2.8 on 2022-12-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('activo', models.BooleanField(default=True)),
                ('fk_canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canton', to='app.canton')),
            ],
        ),
    ]
