# Generated by Django 3.2.8 on 2022-12-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canton',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='fk_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canton_parroquia', to='app.canton'),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('cedula', models.CharField(max_length=11, unique=True)),
                ('celular', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fk_canton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canton_productor', to='app.canton')),
            ],
        ),
    ]
