# Generated by Django 4.1.6 on 2023-02-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_galeria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
