# Generated by Django 3.2.8 on 2022-12-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_parroquia_fk_canton'),
    ]

    operations = [
        migrations.AddField(
            model_name='productor',
            name='fk_parroquia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia_productor', to='app.parroquia'),
            preserve_default=False,
        ),
    ]
