# Generated by Django 4.1.6 on 2023-02-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_galeria_imagen_alter_galeria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='pdfs/')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
