# Generated by Django 3.2.8 on 2022-12-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_productor_fk_parroquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parroquia',
            name='fk_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquiaslist', to='app.canton'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='fk_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cantonlist', to='app.canton'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='fk_parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parroquialist', to='app.parroquia'),
        ),
    ]
