# Generated by Django 3.2.8 on 2022-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221219_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('costo_totoal', models.DecimalField(decimal_places=10, max_digits=19)),
                ('precio_venta', models.DecimalField(decimal_places=10, max_digits=19)),
                ('toneladas', models.DecimalField(decimal_places=10, max_digits=19)),
                ('quintales', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
       
    ]
