# Generated by Django 3.2.8 on 2022-12-23 07:14

from django.db import migrations

def insert_init_data_tipo_productor(apps, schema_editor):
    TipoProductor = apps.get_model('app', 'Tipo_Productor')
    TipoProductor.objects.create(nombre='Puqueño')
    TipoProductor.objects.create(nombre='Mediano')
    TipoProductor.objects.create(nombre='Grande')

def undo_insert_data_tipo_productor(apps, schema_editor):
    TipoProductor = apps.get_model('app', 'Tipo_Productor')
    TipoProductor.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_produccion_tipoproductor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoProductor',
            new_name='Tipo_Productor',
        ),
        migrations.RunPython(insert_init_data_tipo_productor, undo_insert_data_tipo_productor),
    ]
