# Generated by Django 3.2.8 on 2022-12-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_tipoproductor_tipo_productor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='costo_totoal',
            new_name='costo_total',
        ),
        migrations.AddField(
            model_name='produccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fk_productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='listarproductoresproduccion', to='app.productor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='fk_tipo_productor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='tipoproductorlist', to='app.tipo_productor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='fk_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parroquiaslist', to='app.canton'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='year',
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productor',
            name='fk_canton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cantonlist', to='app.canton'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='fk_parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='parroquialist', to='app.parroquia'),
        ),
    ]
