# Generated by Django 3.2.8 on 2022-12-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221226_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='quintales',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='toneladas',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='year',
            field=models.PositiveIntegerField(max_length=4),
        ),
    ]
