# Generated by Django 3.2.8 on 2022-12-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20221226_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='costo_total',
            new_name='hecatarias',
        ),
    ]
