# Generated by Django 3.2.8 on 2022-12-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_costo_total_produccion_hecatarias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='hecatarias',
            new_name='hectarias',
        ),
    ]
