# Generated by Django 3.2.8 on 2022-12-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_hecatarias_produccion_hectarias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='hectarias',
            new_name='hectareas',
        ),
    ]
