# Generated by Django 3.2.8 on 2022-12-28 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_lugar_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_compra', models.PositiveIntegerField(max_length=4)),
                ('cantidad_comprada', models.DecimalField(decimal_places=2, max_digits=19)),
                ('activo', models.BooleanField(default=True)),
                ('fk_lugar', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='intermediariolist', to='app.lugar')),
            ],
        ),
    ]
