# Generated by Django 3.2.8 on 2022-12-28 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_intermediario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediario',
            name='fk_lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lugarlist', to='app.lugar'),
        ),
    ]
