# Generated by Django 3.2.8 on 2022-12-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20221228_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediario_produccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
