# Generated by Django 3.2.8 on 2022-12-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_intermediario_produccion_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intermediario',
            name='cantidad_comprada',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='fk_lugar',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='produccion',
        ),
        migrations.RemoveField(
            model_name='intermediario',
            name='year_compra',
        ),
        migrations.AddField(
            model_name='intermediario',
            name='lugar',
            field=models.CharField(default=0, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediario_produccion',
            name='cantidad_comprada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediario_produccion',
            name='year_compra',
            field=models.PositiveIntegerField(default=False, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produccion',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
