# Generated by Django 3.2.8 on 2022-12-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20221229_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='quintales',
            field=models.PositiveIntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
