# Generated by Django 3.2.8 on 2022-12-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20221229_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intermediario_produccion',
            name='cantidad_comprada',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='quintales',
            field=models.PositiveIntegerField(),
        ),
    ]
