# Generated by Django 3.2.8 on 2022-12-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20221229_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('year', models.PositiveIntegerField(max_length=4)),
                ('recolectado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('amontonado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desgranado', models.DecimalField(decimal_places=2, max_digits=19)),
                ('alquiler_desgranadora', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ensacado_almacenamiento', models.DecimalField(decimal_places=2, max_digits=19)),
                ('control_tratamiento_maiz', models.DecimalField(decimal_places=2, max_digits=19)),
                ('venta', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primera_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primer_control_plagas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('primer_control_enfermedades', models.DecimalField(decimal_places=2, max_digits=19)),
                ('aplicacion_hebricida', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segunda_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segundo_control_plagas', models.DecimalField(decimal_places=2, max_digits=19)),
                ('segundo_control_enfermedades', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tercera_fertilizacion', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tiempo_espera', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desbroce_monte', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quema_maleza', models.DecimalField(decimal_places=2, max_digits=19)),
                ('seleccion_semilla', models.DecimalField(decimal_places=2, max_digits=19)),
                ('aplicacion_herbicida', models.DecimalField(decimal_places=2, max_digits=19)),
                ('desinfeccion_semilla', models.DecimalField(decimal_places=2, max_digits=19)),
                ('siembra', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
