# Generated by Django 3.2.8 on 2022-12-30 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_costoproduccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CostoProduccion',
            new_name='Costo_Produccion',
        ),
    ]
