# Generated by Django 3.2.8 on 2022-12-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_costoproduccion_costo_produccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo_produccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
