# Generated by Django 3.2.8 on 2022-12-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_costo_produccion_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo_produccion',
            name='year',
            field=models.PositiveIntegerField(max_length=4, unique=True),
        ),
    ]
