# Generated by Django 4.1.4 on 2023-01-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_costo_produccion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='costo_produccion',
            name='cosecha_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costo_produccion',
            name='labores_culturales_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costo_produccion',
            name='siembra_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
