# Generated by Django 3.2.8 on 2022-11-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=11)),
                ('apellido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
